### ISSUE TITLE
Out of stack space on IE11?

### ISSUE THREAD

**Issue by mwleinad** [sodatea/get-current-script#4]
Vue includes your polyfill

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/setPublicPath.js

But when I try to use document.currentScript in any js script when in IE11, I get a Out of stack space at

```
function getCurrentScript () {
    if (document.currentScript) {
      return document.currentScript
    }

```

Any idea what would cause this behavior? 

Btw, the way I have it now is to load the original Adam Miller polyfill. Why would that end up running getCurrentScript() from yours?

**Comment by haoqunjiang** [comment]
Yeah it was a bug in v1.0.0. But it's fixed in the current version.
So please delete `package-lock.json`, `yarn.lock`, `node_modules` in your project and then reinstall the dependencies.

**Comment by haoqunjiang** [comment]
The reason for introducing this package is stated in the project README:

> It also works around a [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1620505) when the script is called in a microtask, which makes `document.currentScript` unusable in a webpack dynamic-imported chunk.

**Comment by mwleinad** [comment]
Thanks! That did the trick. 
I uninstalled and reinstalled @vue/cli-service and that upgraded this package to the correct version 1.0.2

**Comment by chasegiunta** [comment]
Hmmm, @mwleinad is there anything else you might have done to get around this.

I've reinstalled @vue/cli-service, and ensured that get-current-script was on 1.0.2 as well, but I'm still getting this issue.

@sodatea Do you have any ideas?

Here is my yarn.lock file...
```json
"@soda/get-current-script@^1.0.0":
  version "1.0.2"
  resolved "https://registry.npmjs.org/@soda/get-current-script/-/get-current-script-1.0.2.tgz#a53515db25d8038374381b73af20bb4f2e508d87"
  integrity sha512-T7VNNlYVM1SgQ+VsMYhnDkcGmWhQdL0bDyGm5TlQ3GBXnJscEClUUOKduWTmm2zCnvNLC1hc3JpuXjs/nFOc5w==
```
Here's some screenshot reference (apologize for the poor quality)
![image](https://user-images.githubusercontent.com/1377169/85180694-ae9b6e00-b249-11ea-84ca-d2a94a2ee4fb.png)

![image](https://user-images.githubusercontent.com/1377169/85180773-dab6ef00-b249-11ea-9d34-7bac04a16960.png)

**Comment by chasegiunta** [comment]
This is so weird. That screenshot is clearly missing some newly added lines in 1.0.2 .

I show this in my nodemodules folder:
```
    var descriptor = Object.getOwnPropertyDescriptor(document, 'currentScript')
    // for chrome
    if (!descriptor && 'currentScript' in document && document.currentScript) {
      return document.currentScript
    }

    // for other browsers with native support for currentScript
    if (descriptor && descriptor.get !== getCurrentScript && document.currentScript) {
      return document.currentScript
    }

```

And then after compilation, those lines are gone in the final bundle (at least per IE11 & the sourcemap). @sodatea Is it possible that babel is removing those somehow? I'm baffled.

**Comment by chasegiunta** [comment]
@sodatea I know you're busy, but just checking back on this to see if you have any ideas.

**Comment by haoqunjiang** [comment]
Is it because some other third-party libraries have bundled their components with an old version of this package?
